### PR TITLE
issue-35: integrate get mapping API

### PR DESCRIPTION
**Pull request by serjoshua**
- use uuid as mapping ID
- integrate get mapping API
- fix for #35

### CODE REVIEW

**Comment by anitacaron** [comment]
Cool! What about all the conditional mapping info? 😄

**Comment by serjoshua** [comment]
Conditional, do you mean the other justifications? Do we have an API for it already? I just integrated the new `/ui/mappings/{mappingId}` API.

**Comment by serjoshua** [comment]
Don't worry, I won't close #35 until everything is finished including the new API for justification once it's available. I just want to merge this initial partial fix to `dev` branch and move with other stuff.

**Comment by anitacaron** [comment]
No, I mean the other data about mappings, the complete list, for example:

```json
{
  "subject_id": "http://purl.obolibrary.org/obo/MP_0031345",
  "predicate_id": "http://www.w3.org/2004/02/skos/core#exactMatch",
  "object_id": "http://purl.obolibrary.org/obo/HP_0000519",
  "mapping_justification": "https://w3id.org/semapv/ManualMappingCuration",
  "subject_label": "developmental cataract",
  "subject_category": null,
  "predicate_label": null,
  "predicate_modifier": null,
  "object_label": "Developmental cataract",
  "object_category": null,
  "author_id": [
    "https://orcid.org/0000-0003-4606-0597",
    "https://orcid.org/0000-0002-6490-7723"
  ],
  "author_label": [],
  "reviewer_id": [],
  "reviewer_label": [],
  "creator_id": [],
  "creator_label": [],
  "license": null,
  "subject_type": null,
  "subject_source": null,
  "subject_source_version": null,
  "object_type": null,
  "object_source": null,
  "object_source_version": null,
  "mapping_provider": null,
  "mapping_cardinality": null,
  "mapping_tool": null,
  "mapping_tool_version": null,
  "mapping_date": "2022-02-01",
  "confidence": 1,
  "subject_match_field": [],
  "object_match_field": [],
  "match_string": [],
  "subject_preprocessing": [],
  "object_preprocessing": [],
  "semantic_similarity_score": null,
  "semantic_similarity_measure": null,
  "see_also": [],
  "other": null,
  "comment": "KidsFirst; ticket https://github.com/mgijax/mammalian-phenotype-ontology/issues/3499"
}
```

**Comment by serjoshua** [comment]
Thanks for this. I can add them now.

**Comment by serjoshua** [comment]
By the way, I might have to _put on hold_ addition of the following fields:
- "author_id"
- "author_label"
- "reviewer_id"
- "reviewer_label"
- "creator_id"
- "creator_label"

I just realized that it will be better to put each pair in a single array of object elements with the ID and label at the same time. I will surely have a hard time identifying on the frontend which label corresponds to which ID. Sample suggestion below:

```
"author": [
  {
    "id": "https://orcid.org/0000-0003-4606-0597",
    "label": ""
  },
  {
    "id": "https://orcid.org/0000-0002-6490-7723"
    "label": ""
  }
]
```

Is it possible? Let me know if it would be a hassle. I will do necessary changes in the frontend model.

**Comment by anitacaron** [comment]
I'll discuss this with Nico.

**Comment by anitacaron** [comment]
You don't need to match the id with the label. As you can see, sometimes the mapping has only the id.

**Comment by anitacaron** [comment]
You can split these mapping data into 4 blocks with the following titles.

**Core mapping metadata**

"subject_id": "http://purl.obolibrary.org/obo/MP_0031345",
"subject_label": "developmental cataract",
"predicate_id": "http://www.w3.org/2004/02/skos/core#exactMatch",
"predicate_label": null,
"object_id": "http://purl.obolibrary.org/obo/HP_0000519",
"object_label": "Developmental cataract"

// It’s a core mapping metadata subblock (give some space between the two blocks)
"subject_category": null,
"subject_type": null,
"subject_source": null,
"subject_source_version": null,
"object_category": null,
"object_type": null,
"object_source": null,
"object_source_version": null,
"mapping_cardinality": null,

**Core attribution data**

"creator_id": [],
"creator_label": [],
"mapping_provider": null,

**Mapping Justification**

"mapping_justification": "https://w3id.org/semapv/ManualMappingCuration",
"confidence": 1,
"subject_match_field": [],
"object_match_field": [],
"match_string": [],
"subject_preprocessing": [],
"object_preprocessing": [],
"mapping_date": "2022-02-01",
"mapping_tool": null,
"mapping_tool_version": null,
"semantic_similarity_score": null,
"semantic_similarity_measure": null,
"author_id": [
  "https://orcid.org/0000-0003-4606-0597",
  "https://orcid.org/0000-0002-6490-7723"
],
"author_label": [],
"reviewer_id": [],
"reviewer_label": [],


**Other**
"license": null,
"see_also": [],
"other": null,
"comment": "KidsFirst; ticket https://github.com/mgijax/mammalian-phenotype-ontology/issues/3499"

**Comment by anitacaron** [comment]
This looks great! It would be clearer if you added the predicate between the subject and object. Instead of two columns, it would be three: Subject, Predicate, Object.

Could you also transform the values inside author_id, creator_id and reviewer_id as a link? They will always be an URL.

Same for the subject/object curie and id, please?

**Pull request merged**
